[package]
name = "benchmark-reporter"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "benchmark_reporter"
path = "src/lib.rs"

[[bin]]
name = "benchmark-reporter"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
benchmark-types = { path = "../crates/benchmark-types" }
clap = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }

[features]
bin = []
