[package]
name = "benchmark-reporter"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "benchmark_reporter"
path = "src/lib.rs"

[[bin]]
name = "benchmark-reporter"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
anyhow = "1"
benchmark-types = { path = "../crates/benchmark-types" }
clap = { version = "4", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2.5"

[features]
bin = []
