[package]
name = "benchmark-token-report"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "benchmark_token_report"
path = "src/lib.rs"

[[bin]]
name = "benchmark-token-report"
path = "src/main.rs"

[dependencies]
benchmark-types = { path = "../crates/benchmark-types" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde_json = "1"

[features]
bin = []
